Controllers/AutoController.cs
using AutoFull.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace AutoFull.Controllers;

public class AutoController : Controller
{
    private readonly AutoFullDbContext _context;
    private readonly UserManager<MyUser> _userManager;

    public AutoController(AutoFullDbContext context, UserManager<MyUser> userManager)
    {
        _context = context;
        _userManager = userManager;
    }

    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        Auto autos = await _context.Autos.Include(a => a.Marca).FirstOrDefaultAsync(m => m.Id == id); // ишет авто в БД

        if (autos == null)
        {
            return NotFound();
        }
        
        return View(autos);
    }

    public async Task<IActionResult> Create()
    {
        ViewBag.MarcaId = new SelectList(_context.Marcas, "Id", "Name");
        
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Auto auto)
    {
        if (ModelState.IsValid)
        {
            _context.Add(auto);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details","Marca", new  {id = auto.MarcaId});
        }

        ViewBag.MarcaId = new SelectList(_context.Marcas, "Id", "Name");
        return View(auto);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        var auto = await _context.Autos.FindAsync(id);
        if (auto != null)
        {
            _context.Autos.Remove(auto);
        }

        await _context.SaveChangesAsync();

        string refererUrl = Request.Headers["Referer"].ToString();
        if (string.IsNullOrEmpty(refererUrl))
        {
            return Redirect(refererUrl);
        }

        return RedirectToAction("Index", "Marca");
    }

    private bool AutoExists(int id)
    {
        return _context.Autos.Any(a => a.Id == id);
    }
}

Controllers/OrderController.cs
using AutoFull.Models;
using AutoFull.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoFull.Controllers;

[Authorize]
public class OrderController : Controller
{
    private readonly AutoFullDbContext _context;
    private readonly UserManager<MyUser> _userManager;
    private readonly EmailService _emailService;

    public OrderController(AutoFullDbContext context, UserManager<MyUser> userManager, EmailService emailService)
    {
        _context = context;
        _userManager = userManager;
        _emailService = emailService;
    }

    //[Authorize(Roles = "Admin")]
    public async Task<IActionResult> Index()
    {
        return View(await _context.Orders.Include(o => o.User).Include(o => o.Marca).ToListAsync());
    }

    [HttpPost]
    public async Task<IActionResult> Create(int cardId, string customerName, string email, string phoneNumber, string address)
    {
        MyUser user = await _userManager.GetUserAsync(User);

        Cart? cart = await _context.Carts
            .Include(ca => ca.CartAutos)
            .ThenInclude(a => a.Auto)
            .FirstOrDefaultAsync(c => c.Id == cardId);

        if (cart == null || !cart.CartAutos.Any())
        {
            return NotFound();
        }

        Order order = new Order()
        {
            UserId = user.Id,
            MarcaId = cart.MarcaId,
            TotalPrice = (double)cart.CartAutos.Sum(a => a.Auto.Price * a.Quantity),
            CustomerName = customerName,
            Phone = phoneNumber,
            Address = address,
            Email = email,
            OrderDate = DateTime.UtcNow,
            Autos = cart.CartAutos.Select(a => a.Auto).ToList()
        };
        
        await _context.Orders.AddAsync(order);
        _context.CartAutos.RemoveRange(cart.CartAutos);
        _context.Carts.Remove(cart);
        await _context.SaveChangesAsync();

        string subject = $"Заказ #{order.Id}";
        string message = $"Детали:\n" +
                         $"Получатель: {customerName}\n" +
                         $"Адрес доставки: {address}\n" +
                         $"Почта получателя: {email}\n" +
                         $"Номер телефона получателя: {phoneNumber}\n" +
                         $"Блюда: \n" +
                         $"{string.Join(", ", order.Autos.Select(a => a.Name).ToList())}";
        
        _emailService.SendEmailAsync(email,subject, message);

        return RedirectToAction("Details", "Marca", new {id = cart.MarcaId});
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - AutoFull</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/AutoFull.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Marca" asp-action="Index">AutoFull</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <ul class="navbar-nav flex-grow-1 d-flex justify-content-start">
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item px-3">
                        <a class="text-decoration-none text-dark" asp-action="Index" asp-controller="Marca">Все марки машин</a>
                    </li>

                    <li class="nav-item px-3">
                        <a class="text-decoration-none text-dark" asp-action="Create" asp-controller="Marca">Добавить марку</a>
                    </li>

                    <li class="nav-item px-3">
                        <a class="text-decoration-none text-dark" asp-action="Create" asp-controller="Auto">Добавить машину</a>
                    </li>

                    <li class="nav-item">
                        <a class="text-decoration-none text-dark" asp-action="Index" asp-controller="Order">Заказ машин</a>
                    </li>
                }
            </ul>

            <ul class="navbar-nav flex-grow-1 d-flex justify-content-end">
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="col-6">
                        <div class="container-fluid">
                            <form class="d-flex" role="search">
                                <i class="search-bi bi bi-search position-absolute top-50 end-0 translate-middle-y me-3"></i>
                                <input id="searchId" class="form-control me-2" type="search" placeholder="Live search..." aria-label="search">
                            </form>
                        </div>
                    </div>
                    
                    <li class="nav-item">
                        <div class="dropstart mx-3">

                            <button class="btn border-0 bg-white" role="button" data-bs-toggle="dropdown" aria-expanded="true">
                                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="#000" class="bi bi-person" viewBox="0 0 16 16">
                                    <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z"/>
                                </svg>
                            </button>

                            <ul class="dropdown-menu">
                                <li>
                                    <a class="nav-link text-dark dropdown-item" asp-route-id="" asp-controller="User" asp-action="Profile">Профиль</a>
                                </li>
                                <li>
                                    <form asp-action="LogOut" asp-controller="Account" class="d-inline">
                                        <input type="submit" class="nav-link text-dark border-0 bg-white dropdown-item" value="Выйти"/>
                                    </form>
                                </li>
                            </ul>
                        </div>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Войти</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Зарегистрироваться</a>
                    </li>
                }
            </ul>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">

    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/34932d7774.js" crossorigin="anonymous"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>