Models/Marca.cs
namespace AutoFull.Models;

public class Marca
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Model { get; set; }
    public string Description { get; set; }
    public string PathToPhoto { get; set; }
    
    public List<Auto> Autos { get; set; }
    public List<Cart> Carts { get; set; }
    public List<Feedback> Feedbacks { get; set; }
    public double AverageRating => Feedbacks.Any() ? Math.Round(Feedbacks.Average(x => x.Rating), 1) : 0.0;

    public Marca()
    {
        Autos = new List<Auto>();
        Carts = new List<Cart>();
        Feedbacks = new List<Feedback>();
    }
}

ViewModels/MarcaViewModel.cs
using AutoFull.Models;

namespace AutoFull.ViewModels;

public class MarcaViewModel
{
    public Marca MarcasDetais { get; set; }
    public MyUser CurrentUser { get; set; }
}

Controllers/MarcaController.cs
using Microsoft.AspNetCore.Mvc;
using AutoFull.Models;
using AutoFull.Repositories;
using AutoFull.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace AutoFull.Controllers
{
    [Authorize]
    public class MarcaController : Controller
    {
        private readonly AutoFullDbContext _context;
        private readonly IUserRepository _userRepository;
        private readonly UserManager<MyUser> _userManager;

        public MarcaController(AutoFullDbContext context, IUserRepository userRepository, UserManager<MyUser> userManager)
        {
            _context = context;
            _userRepository = userRepository;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(string search = "", int page = 1)
        {
            var marcas = string.IsNullOrWhiteSpace(search) ? await _context.Marcas.ToListAsync() : await _context.Marcas.Where(m => m.Name.ToLower().Contains(search) || m.Description.ToLower().Contains(search)).ToListAsync();
            
            int pageSize = 4;
            int marcaCount = marcas.Count();
            List<Marca> marcaList = marcas.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            IndexViewModel vm = new IndexViewModel()
            {
                Marcas = marcaList,
                PageViewModel = new PageViewModel(marcaCount, page, pageSize),
            };
            return View(vm);
        }

        public async Task<IActionResult> GetUsers(int? id)
        {
            if (!id.HasValue)
            {
                return BadRequest();
            }
            
            var user = await _userRepository.GetUserAsync(User);

            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Marca/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marca = await _context.Marcas
                .Include(a => a.Autos)
                .Include(c => c.Carts)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (marca == null)
            {
                return NotFound();
            }

            MyUser user = await _userManager.GetUserAsync(User);

            return View(new MarcaViewModel
            {
                CurrentUser = user,
                MarcasDetais = marca
            });

            //return View(marca);
        }
        
        //GET: Marca/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Marca marca)
        {
            if (ModelState.IsValid)
            {
                await _context.AddAsync(marca);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(marca);
        }
        
        //GET: Marca/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marca = await _context.Marcas.FindAsync(id);
            if (marca == null)
            {
                return NotFound();
            }
            
            return View(marca);
        }
        
        // POST: Marca/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Marca marca)
        {
            if (id != marca.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(marca);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MarcaExists(marca.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(marca);
        }
        
        //GET: Marca/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marca = await _context.Marcas.FirstOrDefaultAsync(m => m.Id == id); // Для поиска объекта Marca по идентификатору.
            if (marca == null)
            {
                return NotFound();
            }
            return View(marca);
        }
        
        // POST: Marca/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var marca = await _context.Marcas.FindAsync(id);
            if (marca != null)
            {
                _context.Marcas.Remove(marca);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MarcaExists(int id)
        {
            return _context.Marcas.Any(e => e.Id == id);
        }
        
        //---------------------------------------------------

            [HttpPost]
            public async Task<IActionResult> AddFeedback(int marcaId, string feedbackText, int rating)
            {
                Marca? marca = await _context.Marcas
                    .Include(a => a.Autos)
                    .Include(e => e.Feedbacks)
                    .ThenInclude(u => u.User)
                    .FirstOrDefaultAsync(m => m.Id == marcaId);
                
                if (marca == null)
                {
                    return NotFound();
                }
                
                if (string.IsNullOrWhiteSpace(feedbackText) || rating <= 0 || rating > 5)
                {
                    Console.WriteLine("Некорректные данные: feedbackText=" + feedbackText + ", rating=" + rating);
                    return BadRequest("Некорректные данные");
                }

                MyUser user = await _userRepository.GetUserAsync(User);

                if ((await _context.Feedbacks.Include(u =>  u.User).AnyAsync(f => f.UserId == user.Id && f.MarcaId == marca.Id)))
                {
                    return BadRequest();
                }
                
                Feedback feedback = new Feedback
                {
                    Rating = rating,
                    Text = feedbackText,
                    CreationDate = DateTime.UtcNow,
                    MarcaId = marcaId,
                    UserId = user.Id
                };

                await _context.Feedbacks.AddAsync(feedback);
                Console.WriteLine("Отзыв добавлен: " + feedbackText); // Лог для проверки
                await _context.SaveChangesAsync();

                

                return PartialView("_FeedbacksPartialView", new MarcaViewModel()
                {
                    CurrentUser = user,
                    MarcasDetais = marca
                });
            }

        public async Task<IActionResult> DeleteFeedback(int marcaId)
        {
            Marca? marca =  await _context.Marcas
                .Include(e => e.Feedbacks)
                .ThenInclude(u => u.User)
                .FirstOrDefaultAsync(m => m.Id == marcaId);
            
            if (marca == null)
            {
                return NotFound("Страница не найдено");
            }
            
            MyUser user = await _userRepository.GetUserAsync(User);

            Feedback? feedback = (await _context.Feedbacks.Include(f => f.User).FirstOrDefaultAsync(f => f.MarcaId == marcaId && f.UserId == user.Id));

            if (feedback == null)
            {
                return NotFound();
            }

            _context.Feedbacks.Remove(feedback);
            await _context.SaveChangesAsync();

            return RedirectToAction("Details", new {id = marca.Id});
        }
    }
}

Views/Marca/Create.cshtml
@model AutoFull.Models.Marca

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Marca</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PathToPhoto" class="control-label"></label>
                <input asp-for="PathToPhoto" class="form-control" />
                <span asp-validation-for="PathToPhoto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Marca/Delete.cshtml
@model AutoFull.Models.Marca

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Marca</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PathToPhoto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PathToPhoto)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Marca/Details.cshtml
    @model AutoFull.ViewModels.MarcaViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row mt-5">
    <div class="col-8 mx-auto">
        <div class="row">
            <div class="col-5">
                <h1 class="mb-3">@Model.MarcasDetais.Name</h1>
                <p class="text-break text-wrap">@Model.MarcasDetais.Description</p>
            </div>

            <div class="col-7">
                <img src="@Model.MarcasDetais.PathToPhoto" alt="Main Photo" class="img-fluid rounded-3">
            </div>
        </div>
        
        @if (User.IsInRole("admin"))
        {
            <h3 class="mb-3">Действия</h3>
            <div class="d-flex">
                <a class="btn btn-danger me-3" asp-action="Delete" asp-controller="Marca" asp-route-id="@Model.MarcasDetais.Id">Удалить</a>
                <a class="btn btn-warning" asp-action="Edit" asp-controller="Marca" asp-route-id="@Model.MarcasDetais.Id">Редактировать</a>
            </div>
        }

        <div class="border-bottom mb-3">
            <h4>
                Рейтинг

                @{
                    int mantissa = (int)Model.MarcasDetais.AverageRating;
                    int countOfFraction = ((Model.MarcasDetais.AverageRating * 10) % 10) > 0 ? 1 : 0;

                    for (int i = 0; i < 5; i++)
                    {
                        if (mantissa > 0)
                        {
                            @: <i class="bi bi-star-fill text-warning"></i>
                            mantissa--;
                        }
                        else
                        {
                            if (countOfFraction > 0)
                            {
                                @: <i class="bi bi-star-half text-warning"></i>
                                countOfFraction--;
                            }
                            else
                            {
                                @: <i class="bi bi-star text-warning"></i>
                            }
                        }
                    }
                }

                @Model.MarcasDetais.AverageRating
            </h4>
        </div>

        <h3>Отзывы</h3>
        <div id="feedbacksBlock" class="mb-3">
            @{
                await Html.RenderPartialAsync("_FeedbacksPartialView", Model);
            }
        </div>

        @if (User.Identity.IsAuthenticated)
        {
            <div class="p-3 border rounded-2 bg-light">
                <h5 class="mb-3">Добавить фото заведения</h5>
                <form id="addPhotoForm" enctype="multipart/form-data">
                    <input id="establishmentId" type="hidden" name="establishmentId" value="@Model.MarcasDetais.Id">
                    <input name="newPhoto" id="fileInput" class="form-control mb-3" type="file" accept="image/*" required/>
                    <input type="submit" class="btn btn-outline-primary" value="Загрузить фото">
                </form>
            </div>
        }

    </div>
</div>

@section Scripts {
    <script>
        let addPhotoForm = $('#addPhotoForm');
        let galleryBlock = $('#galleryBlock');
        let feedbacksBlock = $('#feedbacksBlock');
        let addFeedbackForm = $('#addFeedbackForm');
        let feedbackErrorMsg = $('#feedbackErrorMsg');

        addFeedbackForm.submit(function (event) {
            event.preventDefault();
            let rating = 0;
            let stars = $('.star');
            
            stars.each(function () {
               if ($(this).hasClass('bi-star-fill')) {
                    rating++;
                } 
            });
            
            if (rating > 0) {
                $.ajax({
                    url: '@Url.Action("AddFeedback", "Marca")',
                    type: 'POST',
                    data: {
                        marcaId : '@Model.MarcasDetais.Id',
                        feedbackText : $('#feedbackTextInp').val(),
                        rating : rating
                    },
                    success: function (response) {
                        feedbacksBlock.html(response);
                        $('#feedbackTextInp').val('');
                        fillStar(0);
                    }
                });
            }
            else {
                feedbackErrorMsg.text('Введите оценку');
            }
        });
        
                
        function fillStar(count) {
            let stars = $('.star');
            feedbackErrorMsg.empty();

            stars.each(function () {
                $(this).removeClass('bi-star-fill').addClass('bi-star').removeClass('text-warning');
            });
            
            stars.slice(0, count).each(function () {
                $(this).removeClass('bi-star').addClass('bi-star-fill').addClass('text-warning');
            });
        }
    </script>
}

Views/Marca/Edit.cshtml
@model AutoFull.Models.Marca

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Marca</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PathToPhoto" class="control-label"></label>
                <input asp-for="PathToPhoto" class="form-control" />
                <span asp-validation-for="PathToPhoto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Marca/Index.cshtml
@model AutoFull.ViewModels.IndexViewModel


<div id="indexBlock">
    @{
        await Html.RenderPartialAsync("_IndexPartialView", Model);
    }
</div>

@section Scripts {
    <script>
        let searchInput = $('#searchId'); 
        let indexBlock = $('#indexBlock');
        let page = 1;
        let search = "";

        function getData() {
            $.ajax({
                url: '@Url.Action("Index", "Marca")',
                type: 'GET',
                data: {
                    'search': search,
                    'page': page
                },
                success: function (response) {
                    indexBlock.html($(response).find("#indexBlock").html());
                },
                error: function () {
                    console.error("Ошибка при загрузке данных.");
                }
            });
        }

        searchInput.on("input", function () {
            page = 1;
            search = searchInput.val();
            getData();
        });

        function changePage(nextPage) {
            page = nextPage;
            getData();
        }

        $(document).on("click", ".pagination .page-link", function (event) {
            event.preventDefault();
            let nextPage = $(this).data('page');
            if (nextPage !== page) {
                changePage(nextPage);
            }
        });
    </script>
}

Views/Marca/_FeedbacksPartialView.cshtml
@model AutoFull.ViewModels.MarcaViewModel

<div class="border-bottom mb-3">
    @foreach (Feedback feedback in Model.MarcasDetais.Feedbacks)
    {
        <div class="p-3 border mb-3 rounded-2 bg-light">
            <p>@feedback.CreationDate.ToString("d.MM.yyyy HH:mm"), <a asp-action="Profile" asp-controller="User">@feedback.User.UserName</a></p>
            <p>@feedback.Text</p>
            <div>
                @{
                    int mantissa = feedback.Rating;
                        
                    for (int i = 0; i < 5; i++)
                    {
                        if (mantissa > 0)
                        {
                            <i class="bi bi-star-fill text-warning"></i>
                            mantissa--;
                        }
                        else
                        {
                            <i class="bi bi-star text-warning"></i>
                        }
                    }
                }
            </div>
        </div>
    }
</div>

@if (User.Identity.IsAuthenticated)
{
    <div class="p-3 mb-3 border rounded-2 bg-light">
        @if (Model.MarcasDetais.Feedbacks.Any(e => e.UserId == Model.CurrentUser.Id))
        {
            <h5 class="mb-3">Удалить отзыв</h5>
            <p>У вас уже есть отзыв. Желаете удалить прошлый и добавить новый ?</p>
            <form asp-action="DeleteFeedback" asp-controller="Marca">
                <input type="hidden" name="establishmentId" value="@Model.MarcasDetais.Id">
                <input type="submit" value="Удалить" class="btn btn-outline-danger">
            </form>
        }
        else
        {
            <h5 class="mb-3">Добавить отзыв</h5>

            <div class="mb-3">
                <i onclick="fillStar(1)" style="cursor: pointer;" class="bi bi-star text-warning star"></i>

                <i onclick="fillStar(2)" style="cursor: pointer;" class="bi bi-star text-warning star"></i>

                <i onclick="fillStar(3)" style="cursor: pointer;" class="bi bi-star text-warning star"></i>

                <i onclick="fillStar(4)" style="cursor: pointer;" class="bi bi-star text-warning star"></i>

                <i onclick="fillStar(5)" style="cursor: pointer;" class="bi bi-star text-warning star"></i>
            </div>

            <span class="text-danger my-2" id="feedbackErrorMsg"></span>

            <div>
                <form id="addFeedbackForm">
                    <textarea id="feedbackTextInp" name="feedbackText" class="form-control mb-3" cols="30" rows="5" style="resize: none;"></textarea>
                    <input type="submit" class="btn btn-outline-primary" value="Добавить">
                </form>
            </div>
        }
    </div>
}

Views/Marca/_IndexPartialView.cshtml
@model AutoFull.ViewModels.IndexViewModel

<div class="row">
    @foreach (Marca m in Model.Marcas)
    {
        <div class="col-md-6 col-lg-3 col-sm-6">
            <div class="card border-3 border-primary">
                <a asp-action="Details" asp-controller="Marca" asp-route-id="@m.Id"><img src="@m.PathToPhoto" class="card-img-top img-fluid" alt="#" style="height: 200px"></a>
                <div class="card-body ps-0 pb-0">
                    <a asp-action="Details" asp-controller="Marca" asp-route-id="@m.Id" style="text-decoration: none"><h6 class="text-center">@m.Name</h6></a>
                </div>

                <div class="rating mb-2">
                    @for (int i = 1; i <= 5; i++)
                    {
                    if (i <= m.AverageRating)
                    {
                    <i class="fa-solid fa-star" style="color: #FFD43B;"></i>
                    }
                    else if (i - m.AverageRating < 1)
                    {
                    <i class="fa-solid fa-star-half-stroke" style="color: #FFD43B;"></i>
                    }
                    else
                    {
                    <i class="fa-regular fa-star"></i>
                    }
                    }
                </div>
                <p class="mb-2">(@m.AverageRating, @ViewBag.FeedbackCount отзывов)</p>

                <div>
                    <i class="fa-solid fa-camera"></i>
                    <span>@m.Feedbacks.Count фотографий</span>
                </div>
                
            </div>
        </div>
    }
</div>

<div class="d-flex justify-content-center mt-5">
    <nav>
        <ul class="pagination text-success">
            @if (Model.PageViewModel.HasPreviousPage)
            {
                <li class="page-item">
                    <button type="button" onclick="changePage('@(Model.PageViewModel.PageNumber - 1)')" class="page-link">Предыдущая</button>
                </li>
            }
            else
            {
                <li class="page-item disabled">
                    <a class="page-link">Предыдущая</a>
                </li>
            }
            
            @if (Model.PageViewModel.PageNumber > 3)
            {
                <li class="page-item disabled">
                    <span class="page-link">...</span>
                </li>
            }
            @for (int i = Math.Max(1, Model.PageViewModel.PageNumber - 2); i < Model.PageViewModel.PageNumber; i++)
            {
                <li class="page-item">
                    <button class="page-link" type="button" onclick="changePage('@i')"  >@i</button>
                </li>
            }
            <li class="page-item active">
                <button class="page-link" type="button" onclick="changePage('@Model.PageViewModel.PageNumber')" >@Model.PageViewModel.PageNumber</button>
            </li>
            @for (int i = Model.PageViewModel.PageNumber + 1; i <= Math.Min(Model.PageViewModel.TotalPages, Model.PageViewModel.PageNumber + 2); i++)
            {
                <li class="page-item">
                    <button class="page-link" type="button" onclick="changePage('@i')">@i</button>
                </li>
            }

            @if (Model.PageViewModel.PageNumber < Model.PageViewModel.TotalPages - 2)
            {
                <li class="page-item disabled">
                    <span class="page-link disabled">...</span>
                </li>
            }

            @if (Model.PageViewModel.HasNextPage)
            {
                <li class="page-item">
                    <button class="page-link" type="button" onclick="changePage('@(Model.PageViewModel.PageNumber+1)')">Следующая</button>
                </li>
            }
            else
            {
                <li class="page-item disabled">
                    <a class="page-link">Следующая</a>
                </li>
            }
        </ul>
    </nav>
</div>

Views/Marca/_MarcaTable.cshtml
@model IEnumerable<AutoFull.Models.Marca>

@foreach (var item in Model)
{
    <tr>
        <td>@Html.DisplayFor(modelItem => item.Name)</td>
        <td>@Html.DisplayFor(modelItem => item.Model)</td>
        <td>@Html.DisplayFor(modelItem => item.Description)</td>
        <td>@Html.DisplayFor(modelItem => item.PathToPhoto)</td>
        <td>
            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
        </td>
    </tr>
}